<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::table('exchange_rates')->where('source', 'derived')->delete();
        DB::table('rate_histories')->where('source', 'derived')->delete();
    }

    public function down(): void
    {
        // Intentionally empty — derived data is regenerated by UpdateExchangeRatesJob.
    }
};
